### ISSUE TITLE
Enhance Rocket.chat message

### ISSUE THREAD

**Issue by oliviermaridat** [kanboard/plugin-rocketchat#5]
Instead of

"[Project] John Doe moved task #900989 to column "Done" (Name of the task) - [view this task on Kanboard](https://kanboard.net)"

is it possible to have:

"[Project] John Doe moved task [#900989 "Name of the task"](https://kanboard.net) to column "Done"

?

I know that notification message are generated by EventBuilders, so changing this may involve regex to search for #900989 and replace it by [#900989 "Name of the task"](https://kanboard.net). What do you think?

It could be also really great to add comment or description for **new** comment or description events. But how can we get them?

**Comment by DaBlitzStein** [comment]
Aditionally, change the icon and the name of the user can be very useful. For reasons. :smile_cat:

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
